---
title: "The Financial Education Project"
date: ""
output: html_document
---

*There are some empty links at the moment because a server went down (5minuefinance.org).  It also hosted many of the web apps (which will also be down).  I will try and push is all to a new server but it will take a while.*

This site organizes a set of interactive presentations used in common undergraduate finance courses. What makes these presentations unique is the focus on applying the concepts learned using real data.  To that end we use:

1.  Interactive applications which allow the student to explore a given concept.
2.  Code which the student can run and modify which illustrates a concept.  I provide code across multiple languages, though I try to focus on Python, C++, and R.

I also embed short video lectures where it seems advantageous to learning. 

If there is a presentation you would like to request, [open an issue on this repository](https://github.com/financial-education/financial-education.github.io).  Also feel free to contribute to presentations by issuing pull requests.

The site is organized into *courses*.  To see a course outline with presentation links, use the ‘Courses’ dropdown box above. ​I am constantly adding materials, and some topics may not yet be covered. In some cases, you will see links to concepts that are "under construction" in GitHub.  Feel free to contribute to these presentations or build your own. 

